name: Deploy documentation

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install deps
              run: npm install

            - name: Build
              run: npm run docs

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  publish_branch: docs
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs
                  cname: dotperm.js.org
